In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [49]:
def data_split(vectors_df, X_label='X_tfidf', random_state=12):
    X = vectors_df[X_label].iat[0]
    X_train, X_test, y_train, y_test = train_test_split(X, reviews_df['ratings'], test_size=0.33, random_state=random_state)
    ## x is scipy.sparse.csr.csr_matrix and y is  pandas.core.series.Series,
    # [type(y) for y in [X_train, X_test, y_train, y_test]]
    return X_train, X_test, y_train, y_test

def add_data_splits(vectors_df):
    test_train_splits_df = pd.DataFrame()
    random_state=12
    labels, X_trains, X_tests, y_trains, y_tests = list(), list(), list(), list(), list()
    for label in vectors_df.columns:
        X_train, X_test, y_train, y_test = data_split(vectors_df, label, random_state)
        labels.append(label)
        X_trains.append(X_train)
        X_tests.append(X_test)
        y_trains.append(y_train)
        y_tests.append(y_test)
    test_train_splits_df['label'] = labels
    test_train_splits_df['random_state'] = random_state
    test_train_splits_df['X_train'] = X_trains
    test_train_splits_df['X_test'] = X_tests
    test_train_splits_df['y_train'] = y_trains
    test_train_splits_df['y_test'] = y_tests
    return test_train_splits_df

In [56]:
def main():
    reviews_df = pd.read_pickle('./data/reviews_df.pickle')
    vectors_df = pd.read_pickle('./data/vectors_df.pickle')
    test_train_splits_df = add_data_splits(vectors_df)
    test_train_splits_df.to_pickle('./data/test_train_splits_df.pickle')
    test_train_splits_df_loaded= pd.read_pickle('./data/test_train_splits_df.pickle')
    return test_train_splits_df_loaded.head()

In [57]:
main()

,label,random_state,X_train,X_test,y_train,y_test
0,X_cnt_mono_bi,12,"(0, 10008)\t1\n (0, 14594)\t5\n (0, 4882)\...","(0, 10008)\t3\n (0, 14594)\t2\n (0, 14144)...",87 1 29 1 83 -1 78 1 39 1 ....,41 1 17 -1 21 1 14 1 31 -1 15 ...
1,X_tfidf_mono_bi,12,"(0, 16044)\t0.06567356270566224\n (0, 9070)...","(0, 1783)\t0.049118210484760894\n (0, 11260...",87 1 29 1 83 -1 78 1 39 1 ....,41 1 17 -1 21 1 14 1 31 -1 15 ...
2,X_cnt,12,"(0, 2901)\t1\n (0, 4186)\t5\n (0, 1513)\t1...","(0, 2901)\t3\n (0, 4186)\t2\n (0, 4131)\t2...",87 1 29 1 83 -1 78 1 39 1 ....,41 1 17 -1 21 1 14 1 31 -1 15 ...
3,X_tfidf,12,"(0, 4134)\t0.09222383602374135\n (0, 3134)\...","(0, 3268)\t0.07106129322977137\n (0, 2697)\...",87 1 29 1 83 -1 78 1 39 1 ....,41 1 17 -1 21 1 14 1 31 -1 15 ...